export default class LanguageModel {
	constructor() {
		this.languages = ['en','fi'];
		this.selected = 'en';
		this.translation = {
			'en':{
				'USER_LOGIN_TITLE':'Login',
				'USER_EMAIL':'Email',
				'USER_PASSWORD':'Password',
				'USER_LOGIN_BTN_TXT':'Login',
				'USER_OPEN_SIGNUP_FORM':'Open signup form &raquo;',
				'USER_SIGNUP_TITLE':'Signup',
				'USER_SIGNUP_BTN_TXT':'Signup',
				'USER_INFO':'User Info',
				'USER_LOGOUT':'LOGOUT',
				'MENU_D_A_LABEL':'District A',
				'MENU_D_B_LABEL':'District B',
				'MENU_D_C_LABEL':'District C',
				'MENU_D_D_LABEL':'District D',
				'MENU_D_E_LABEL':'District E',
				'MENU_TITLE':'Positive Energy Districts',
				'MENU_DESCRIPTION':'The project is funded by EU’s Horizon 2020 programme and is a part of the Smart Cities and Communities (SCC) theme.',
				'SOLAR_PANELS':'SOLAR PANELS',
				'GRID_TEXT':'GRID',
				'DA_BACK':'BACK',
				'DA_CANCEL':'CANCEL',
				'DA_DESCRIPTION':'This view will contain all components for District A.',
				'DAA_TITLE':'Total Consumption',
				'DAB_TITLE':'Solar energy',
				'DAC_TITLE':'Lights and appliances',
				'DAD_TITLE':'Kitchen appliances',
				'DAE_TITLE':'HPAC',
				'DAF_TITLE':'Other',
				'DAG_TITLE':'Cooler machines and equipment',
				'DAHA_TITLE':'Cooler machines',
				'DAHB_TITLE':'Cooler equipment',
				'DAI_TITLE':'Geothermal energy',
				'DAA_POWER':'Power',
				'DAA_ENERGY':'Energy',
				'DAW_SEL_TIMERANGE':'Select timerange for database query:',
				'AUTO_UPDATE_MSG_1':'Chart is automatically updated once every',
				'AUTO_UPDATE_MSG_1_B':'Power consumption values are automatically updated once every',
				'AUTO_UPDATE_MSG_2':'seconds',
				'AUTO_UPDATE_MSG_3':'Chart is NOT automatically updated',
				'ADJUST_UPDATE_INTERVAL':'Adjust the update interval (0-60s):'
			},
			'fi':{
				'USER_LOGIN_TITLE':'Kirjautuminen',
				'USER_EMAIL':'Sähköposti',
				'USER_PASSWORD':'Salasana',
				'USER_LOGIN_BTN_TXT':'KIRJAUDU SISÄÄN',
				'USER_OPEN_SIGNUP_FORM':'Rekisteröityminen &raquo;',
				'USER_SIGNUP_TITLE':'Rekisteröityminen',
				'USER_SIGNUP_BTN_TXT':'Rekisteröidy',
				'USER_INFO':'Käyttäjätiedot',
				'USER_LOGOUT':'KIRJAUDU ULOS',
				'MENU_D_A_LABEL':'Alue A',
				'MENU_D_B_LABEL':'Alue B',
				'MENU_D_C_LABEL':'Alue C',
				'MENU_D_D_LABEL':'Alue D',
				'MENU_D_E_LABEL':'Alue E',
				'MENU_TITLE':'Energiataseeltaan positiivinen alue',
				'MENU_DESCRIPTION':'Hanke saa rahoitusta EU:n Horizon 2020 -ohjelmasta. Se kuuluu Smart Cities and Communities (SCC) -teemaan.',
				'SOLAR_PANELS':'AURINKOPANEELIT',
				'GRID_TEXT':'SÄHKÖVERKKO',
				'DA_BACK':'TAKAISIN',
				'DA_CANCEL':'PERU',
				'DA_DESCRIPTION':'Tähän näyttöön kaikki tämän alueen komponentit.',
				'DAA_TITLE':'Kokonaiskulutus',
				'DAB_TITLE':'Aurinkoenergia',
				'DAC_TITLE':'Valaistus ja laitteet',
				'DAD_TITLE':'Keittiön laitteet',
				'DAE_TITLE':'LVI',
				'DAF_TITLE':'Muut',
				'DAG_TITLE':'Kylmäkoneet ja kylmälaitteet',
				'DAHA_TITLE':'Kylmäkoneet',
				'DAHB_TITLE':'Kylmälaitteet',
				'DAI_TITLE':'Maalämpö',
				'DAA_POWER':'Teho',
				'DAA_ENERGY':'Energia',
				'DAW_SEL_TIMERANGE':'Valitse kuvaajan aikaikkuna:',
				'AUTO_UPDATE_MSG_1':'Kuvaaja päivittyy automaattisesti kerran',
				'AUTO_UPDATE_MSG_1_B':'Teholukemat päivittyvät automaattisesti kerran',
				'AUTO_UPDATE_MSG_2':'sekunnissa',
				'AUTO_UPDATE_MSG_3':'Kuvaaja EI päivity automaattisesti',
				'ADJUST_UPDATE_INTERVAL':'Säädä päivitystaajuutta (0-60s):'
			}
		}
	}
}
