export default class LanguageModel {
	constructor() {
		this.languages = ['en','fi'];
		this.selected = 'fi';
		this.translation = {
			'en':{
				'USER_LOGIN_TITLE':'Login',
				'USER_EMAIL':'Email',
				'USER_PASSWORD':'Password',
				'USER_REGCODE':'Registration code',
				'USER_LOGIN_BTN_TXT':'Login',
				'USER_OPEN_SIGNUP_FORM':'Open signup form &raquo;',
				'USER_SIGNUP_TITLE':'Signup',
				'USER_SIGNUP_BTN_TXT':'Signup',
				'USER_SIGNUP_TABLET_TXT':'Check the checkbox below if you want a tablet computer. Due to limited number of tablets in this pilot, please be quick.',
				'USER_SIGNUP_TABLET_CHECKBOX_LABEL':'Yes, I want a tablet.',
				'USER_SIGNUP_CONSENT_OK_1':'I have read the ',
				'USER_SIGNUP_GDPR_LINK_TXT':'GDPR statement',
				'USER_SIGNUP_CONSENT_OK_2':' and given my consent in ',
				'USER_SIGNUP_CONSENT_LINK_TXT':'consent form.',
				'USER_SIGNUP_APARTMENT_ADDRESS':'Address',
				'USER_SIGNUP_APARTMENT_LETTER':'Letter',
				'USER_SIGNUP_APARTMENT_NUMBER':'Number',
				'USER_SIGNUP_APARTMENT_NOT_SELECTED':'Not selected',
				'USER_SIGNUP_APARTMENT_MUST_INPUT':'Must input <b>Apartment number</b>',
				'HELP_INFO_TITLE':'Making City -pilot',
				'HELP_INFO_THANKS':'Thank you. You have now signed to MakingCity -pilot. Please login.',
				'HELP_INFO_1':'You can view <b>building</b> measurements without signup or login.',
				'HELP_INFO_2':'You can view measurements from your <b>apartment</b> and give feedback about your <b>apartment</b> by signing and logging in.',
				'HELP_INFO_3':'',
				'HELP_INFO_4':'',
				'HELP_INFO_5':'',
				'COMING_SOON':'COMING SOON!',
				'USER_PAGE_ELECTRICITY':'Electricity',
				'USER_PAGE_HEATING':'Heating',
				'USER_PAGE_WATER':'Water',
				'GRID_PAGE_TITLE':'The Grid Page',
				'GRID_PAGE_DESCRIPTION':'Here you will find more information about the aggregated load (from Fingrid open data). Values are updated once every 3 minutes.',
				'GRID_PAGE_PRICE':'Price',
				'SOLAR_PAGE_TITLE':'The Solar Page',
				'SOLAR_PAGE_DESCRIPTION':'Solar power generation forecast for the next 36 hours. Updated hourly.',
				'SOLAR_ENERGY':'Solar power',
				'SOLAR_ENERGY_POWER':'Power',
				'ENVIRONMENT_PAGE_TITLE':'The Environment Page',
				'ENVIRONMENT_PAGE_DESCRIPTION':'Here you will find more information about the environmental load of the energy used.',
				'ENVIRONMENT_PAGE_AXIS_TITLE':'Emissions gCO2/kWh',
				'ENVIRONMENT_PAGE_CONS_TOOLTIP':'Consumed',
				'ENVIRONMENT_PAGE_PROD_TOOLTIP':'Produced',
				'ENVIRONMENT_PAGE_CONS_LEGEND_LABEL':'Consumed',
				'ENVIRONMENT_PAGE_PROD_LEGEND_LABEL':'Produced',
				'ENVIRONMENT_PAGE_LATEST_CONSUMPTION':'Latest consumption',
				'ENVIRONMENT_PAGE_AVERAGE_CONSUMPTION':'Average',
				'USER_PROPS_TITLE':'User Properties',
				'USER_PROPS_DESCRIPTION':'Here you will find your information and settings.',
				'USER_ENERGY_PRICES_TITLE':'Energy price',
				'USER_ENERGY_PRICES_DESCRIPTION':'Give prices from your contract so that we can calculate prices for each period.',
				'USER_ENERGY_PRICES_MONTHLY':'Monthly price: ',
				'USER_ENERGY_PRICES_MONTHLY_UNIT':'€/month',
				'USER_ENERGY_PRICES_ENERGY':'Energy price: ',
				'USER_ENERGY_PRICES_ENERGY_UNIT':'cnt/kWh',
				'USER_ENERGY_PRICES_TRANSFER':'Network price: ',
				'USER_ENERGY_PRICES_TRANSFER_UNIT':'cnt/kWh',
				'USER_ENERGY_PRICE_SAVED_OK':'New price saved.',
				'USER_PROPS_CONSENT':'Click this link to read the ',
				'USER_PROPS_ADMIN_DESCRIPTION':'Admin can view and edit RegCodes, view Users and associated ReadKeys.',
				'USER_PROPS_ADMIN_REGCODES':'RegCodes',
				'USER_PROPS_ADMIN_REGCODES_CREATE_BTN_TXT': 'Create new',
				'USER_PROPS_ADMIN_USERS':'Users',
				'USER_PROPS_ADMIN_CONFIGS':'Configs',
				'USER_PROPS_ADMIN_FEEDBACKS':'Feedbacks',
				'USER_CONSENT_TXT':'You can also view your ',
				'USER_CONSENT_LINK_TXT':'consent form.',
				'USER_GDPR_TXT':'You can also view the ',
				'USER_GDPR_LINK_TXT':'informed consent (GDPR).',
				'ADMIN_START_LABEL':'Start',
				'ADMIN_END_LABEL':'End',
				'USER_PROPS_CHANGE_PASSWORD_BTN_TXT':'Change your password',
				'USER_CHANGE_PASSWORD_TITLE':'Change password',
				'USER_OLD_PASSWORD':'Old password',
				'USER_NEW_PASSWORD':'New password',
				'USER_DATA_PERIOD':'Period',
				'USER_DATA_PERIOD_DAY':'24h',
				'USER_DATA_PERIOD_WEEK':'Week',
				'USER_DATA_PERIOD_MONTH':'Month',
				'USER_DATA_TARGET':'Target',
				'USER_DATA_UPPER_LIMIT':'Upper limit',
				'USER_DATA_LOWER_LIMIT':'Lower limit',
				'USER_DATA_WATER_HOT':'HOT (L)',
				'USER_DATA_WATER_COLD':'COLD (L)',
				'USER_ELECTRICITY_TITLE':'Electricity',
				'USER_ELECTRICITY_DESCRIPTION':'Here you will find more information about your electricity consumption.',
				'USER_ELECTRICITY_CHART_TITLE':'Electricity consumption',
				'USER_CHART_X_DAYS':'days',
				'USER_CHART_X_DAYS_WAIT':'Electricity consumption data not available yet... check tomorrow again.',
				'USER_ELECTRICITY_TARGETS_TITLE':'Targets for 24h energy consumption',
				'USER_ELECTRICITY_TARGETS_DESCRIPTION':'Give upper and lower limits and target value for electricity consumption <b>in one day</b>.',
				'USER_TARGETS_ALARM_COUNT_DESCRIPTION':'Numbers indicate alarm count for last 30 days when current limits are used.',
				'USER_HEATING_TITLE':'Heating',
				'USER_HEATING_DESCRIPTION':'Here you will find more information about your heating.',
				'USER_HEATING_CHART_TITLE':'Temperature and humidity',
				'USER_HEATING_CHART_LEGEND_TEMPERATURE':'Temperature',
				'USER_HEATING_CHART_LEGEND_HUMIDITY':'Humidity',
				'USER_HEATING_CHART_AVERAGE':'Average',
				'USER_HEATING_FEEDBACK_PROMPT':'Give feedback: how do you feel about the apartment temperature today? Select smiley and send feedback.',
				'USER_HEATING_SEND_FEEDBACK':'Send feedback',
				'USER_HEATING_FEEDBACK_OK':'Thank you for your feedback!',
				'USER_HEATING_TARGETS_TITLE':'Targets for heating',
				'USER_HEATING_TARGETS_BOTH_DESCRIPTION':'Give upper and lower limits and target value for temperature and humidity.',
				'USER_TARGET':'Target: ',
				'USER_UPPER_LIMIT':'Upper limit: ',
				'USER_LOWER_LIMIT':'Lower limit: ',
				'USER_TARGET_SAVED':'New target/limit saved.',
				'USER_WATER_TITLE':'Water',
				'USER_WATER_DESCRIPTION':'Here you will find more information about your water consumption.',
				'USER_WATER_CHART_TITLE':'Water consumption',
				'USER_WATER_CHART_TITLE_30_DAYS':'Water consumption 30 days',
				'USER_WATER_CHART_LEGEND_HOT':'Hot',
				'USER_WATER_CHART_LEGEND_COLD':'Cold',
				'USER_WATER_TARGETS_TITLE':'Targets for 24h water consumption',
				'USER_WATER_TARGETS_BOTH_DESCRIPTION':'Give upper and lower limits and target value for water consumption <b>in one day</b>.',
				'USER_ALARM_TITLE':'Alarms',
				'USER_ALARM_DESCRIPTION':'Here you will find a list of alarms and other useful messages from the system.',
				'USER_ALARM_CHART_TITLE':'Count',
				'USER_ALARM_VIEW_TABLE_HEADER_TYPE':'Type',
				'USER_ALARM_VIEW_TABLE_HEADER_COUNT':'Count',
				'USER_ALARM_VIEW_TABLE_HEADER_DETAILS':'&nbsp;',
				'USER_ALARM_VIEW_HEATING_TEMPERATURE_UPPER_LIMIT':'Heating Temperature Upper Limit',
				'USER_ALARM_VIEW_HEATING_TEMPERATURE_LOWER_LIMIT':'Heating Temperature Lower Limit',
				'USER_ALARM_VIEW_HEATING_HUMIDITY_UPPER_LIMIT':'Heating Humidity Upper Limit',
				'USER_ALARM_VIEW_HEATING_HUMIDITY_LOWER_LIMIT':'Heating Humidity Lower Limit',
				'USER_ALARM_VIEW_WATER_HOT_UPPER_LIMIT':'Water Hot Upper Limit',
				'USER_ALARM_VIEW_WATER_HOT_LOWER_LIMIT':'Water Hot Lower Limit',
				'USER_ALARM_VIEW_WATER_COLD_UPPER_LIMIT':'Water Cold Upper Limit',
				'USER_ALARM_VIEW_WATER_COLD_LOWER_LIMIT':'Water Cold Lower Limit',
				'USER_ALARM_VIEW_ENERGY_UPPER_LIMIT':'Energy Upper Limit',
				'USER_ALARM_VIEW_ENERGY_LOWER_LIMIT':'Energy Lower Limit',
				'USER_ALARM_DETAILS_DESCRIPTION':'Alarm count for each day for last 30 days',
				'DISTRICT_A_LABEL':'S-Arina',
				'DISTRICT_B_LABEL':'Sivakka 1',
				'DISTRICT_C_LABEL':'Sivakka 2',
				'DISTRICT_D_LABEL':'School',
				'DISTRICT_E_LABEL':'Sivakka 3',
				'DISTRICT_F_LABEL':'YIT 1',
				'MENU_TITLE':'Positive Energy Districts',
				'MENU_DESCRIPTION':'<a href="http://makingcity.eu/" target="_blank" rel="noreferrer noopener" aria-label="This is an external link (opens in a new tab)">THE MAKING-CITY PROJECT</a> is funded by EU’s Horizon 2020 programme and is a part of the Smart Cities and Communities (SCC) theme.',
				'MENU_VISIT_COUNT':'visit count',
				'SOLAR_PANELS':'SOLAR PANELS',
				'GRID_TEXT':'GRID',
				'DA_BACK':'BACK',
				'DA_CANCEL':'CANCEL',
				'DA_SAVE':'SAVE',
				'DAA_TITLE':'Grid',
				'DAB_TITLE':'Solar power',
				'DAC_TITLE':'Lights and appliances',
				'DAD_TITLE':'Kitchen appliances',
				'DAE_TITLE':'HPAC',
				'DAF_TITLE':'Other',
				'DAG_TITLE':'Compressors, Cooler equipments and Heating',
				'DAP_TITLE_A':'District',
				'DAP_TITLE_B':'heating',
				'DAP_TITLE_C':'network',
				'DAHA_TITLE':'Compressors',
				'DAHB_TITLE':'Cooler equipment',
				'DAHC_TITLE':'Cooling',
				'DAHD_TITLE':'Heating',
				'DAI_TITLE':'Geothermal power',
				'DAA_POWER':'Power',
				'DAA_ENERGY':'Energy',
				'DAW_SEL_TIMERANGE':'Select timerange for database query:',
				'DBA_TITLE':'Grid',
				'DBB_TITLE':'Solar power',
				'DBD_TITLE':'Apartments',
				'DBE_TITLE_1':'SAUNA,',
				'DBE_TITLE_2':'lights,',
				'DBE_TITLE_3':'etc.',
				'DBF_TITLE_1':'Heating',
				'DBF_TITLE_2':'system',
				'DBG_TITLE_1':'Exthaus air',
				'DBG_TITLE_2':'recovery',
				'DBH_TITLE_1':'Wastewater',
				'DBH_TITLE_2':'recovery',
				'DBI_TITLE_1':'District',
				'DBI_TITLE_2':'heating',
				'DBI_TITLE_3':'network',
				'DBJ_TITLE_1':'Heating',
				'DBJ_TITLE_2':'devices',
				'DBK_TITLE_1':'Hot',
				'DBK_TITLE_2':'water',
				'ADMIN_EDIT_POINT_ID_TITLE':'PointId code',
				'ADMIN_EDIT_POINT_ID_DESCRIPTION':'You can change the users PointId code',
				'ADMIN_EDIT_POINT_ID_LABEL':'PointId code',
				'CANCEL':'CANCEL',
				'SAVE':'&nbsp;SAVE&nbsp;',
				'UPDATE':'UPDATE',
				'BACK':'&nbsp;BACK&nbsp;',
				'OK':'&nbsp;&nbsp;&nbsp;&nbsp;OK&nbsp;&nbsp;&nbsp;&nbsp;',
				'AUTO_UPDATE_MSG_1':'Chart is automatically updated once every',
				'AUTO_UPDATE_MSG_1_B':'Power consumption values are automatically updated once every',
				'AUTO_UPDATE_MSG_2':'seconds',
				'AUTO_UPDATE_MSG_3':'Chart is NOT automatically updated',
				'ADJUST_UPDATE_INTERVAL':'Adjust the update interval (0-60s):',
				'UPDATED_HEADER_TEXT':'Values updated: ',
				'CONSENT_TITLE':'SUOSTUMUS',
				'CONSENT_TEXT_A':'Vahvistan lukeneeni ja ymmärtäneeni tutkimustiedotteen ja sen liitteenä olleen tietosuojailmoituksen. Vahvistan, että tiedossani ei ole tutkimustiedotteessa esitettyä poissulkukriteeriä ja/tai täytän valintakriteerit. Minulla on ollut mahdollisuus harkita saamaani tietoa, esittää kysymyksiä ja olen saanut kysymyksiini riittävän vastauksen.',
				'CONSENT_CHECK_A':'Annan suostumukseni <b>tutkimukseen osallistumiseen</b>. Minulla on oikeus keskeyttää osallistuminen väliaikaisesti tai toistaiseksi (jättäytyä tutkimuksen vaiheen ulkopuolelle) tai peruuttaa suostumus, milloin tahansa ilman erityistä syytä ja syytä kertomatta.',
				'CONSENT_CHECK_B':'Annan suostumukseni <b>henkilötietojen käsittelyyn tutkimuksessa</b>. Minulla on oikeus, milloin tahansa perua suostumukseni ilman erityistä syytä ja syytä kertomatta.',
				'CONSENT_TEXT_B':'Voin perua yllä olevan suostumukseni, mutta ymmärrän aineiston julkiseksi saattamisen jälkeen poistamisen rajoitteet.',
				'GDPR_TITLE':'Tietosuojailmoitus tutkimukseen',
				'GDPR_DESCRIPTION':'Tietosuojailmoitus perustuu EU:n yleiseen tietosuoja-asetukseen (2016/679, "tietosuoja-asetus") ja tietosuojalakiin (1050/2018).',
				'GDPR_CHAPTER_1':'1. Tutkimuksen nimi ja kesto',
				'GDPR_CHAPTER_1A':'Tutkimuksen nimi: iFLEX (Intelligent Assistants for Flexibility Management',
				'GDPR_CHAPTER_1B':'Tutkimuksen kestoaika: 1.11.2020 - 31.10.2023',
				'GDPR_CHAPTER_2':'2. Rekisterinpitäjä(-t), tietosuojavastaava ja yhteyshenkilö(-t)',
				'GDPR_CHAPTER_2A':'Teknologian Tutkimuskeskus VTT Oy (”VTT”), Y-tunnus: 2647375-4, Vuorimiehentie 3, 02150 Espoo',
				'GDPR_CHAPTER_2AA':'Tietosuojavastaava:',
				'GDPR_CHAPTER_2AAA':'Nimi: Seppo Viinikainen',
				'GDPR_CHAPTER_2AAB':'Osoite: Teknologian tutkimuskeskus VTT Oy, Koivurannantie 1, 40400 Jyväskylä',
				'GDPR_CHAPTER_2AAC':'Sähköposti: <a href="mailto:Seppo.Viinikainen@vtt.fi">Seppo.Viinikainen@vtt.fi</a> (tietosuojavastaava) tai <a href="mailto:tietosuoja@vtt.fi">tietosuoja@vtt.fi</a> (tietosuojavastaava, tietoturvapäällikkö, HR ja lakimies)',
				'GDPR_CHAPTER_2AB':'Tutkimuksesta vastaavan yhteyshenkilön tai tutkimusryhmän yhteystiedot:',
				'GDPR_CHAPTER_2ABA':'Nimi: Markus Taumberger, Jussi Kiljander, Anne Immonen',
				'GDPR_CHAPTER_2ABB':'Osoite: Teknologian tutkimuskeskus VTT Oy, Kaitoväylä 1, 90571 Oulu',
				'GDPR_CHAPTER_2ABC':'Sähköposti: <a href="mailto:iFLEX-Info@vtt.fi">iFLEX-Info@vtt.fi</a>',
				'GDPR_CHAPTER_2B':'Muut yhteisrekisterinpitäjät:',
				'GDPR_CHAPTER_2BA':'<b>Smart Com d.o.o.</b>',
				'GDPR_CHAPTER_2BA_EMAIL':'Sähköposti: skrbnikVOP@smart-com.si',
				'GDPR_CHAPTER_2BB':'<b>Enerim Oy</b>',
				'GDPR_CHAPTER_2BB_EMAIL':'Sähköposti: heikki.hiltunen@enerim.com',
				'GDPR_CHAPTER_2BC':'<b>Jozef Stefan Institute</b>',
				'GDPR_CHAPTER_2BC_EMAIL':'Sähköposti: dusan.gabrijelcic@jsi.si',
				'GDPR_CHAPTER_2BD':'<b>ATHENS UNIVERSITY OF ECONOMICS AND BUSINESS (AUEB)</b>',
				'GDPR_CHAPTER_2BD_EMAIL':'Sähköposti: Maria Antonopoulou, dpo@aueb.gr yhteyshenkilö: Stamoulis George, gstamoul@aueb.gr',
				'GDPR_CHAPTER_2BE':'<b>Intracom SA Telecom Solutions</b>',
				'GDPR_CHAPTER_2BE_EMAIL':'Sähköposti: labil@intracom-telecom.com (yhteyshenkilö)',
				'GDPR_CHAPTER_2BF':'<b>ELEKTRO CELJE, podjetje za distribucijo električne energije, d.d.</b>',
				'GDPR_CHAPTER_2BF_EMAIL':'Sähköposti: anton.kos@elektro-celje.si; mojca.potecin@elektro-celje.si',
				'GDPR_CHAPTER_2BG':'<b>Caverion Oyj</b>',
				'GDPR_CHAPTER_2BG_EMAIL':'Sähköposti: olli.nummelin@caverion.com',
				'GDPR_CHAPTER_2BH':'<b>In-JeT ApS</b>',
				'GDPR_CHAPTER_2BH_EMAIL':'Sähköposti: tfs@in-jet.dk',
				'GDPR_CHAPTER_2BI':'<b>ECE d.o.o.</b>',
				'GDPR_CHAPTER_2BI_EMAIL':'Sähköposti: gasper.ravnak@ece.si ; andraz.javernik@ece.si',
				'GDPR_CHAPTER_2BJ':'<b>HERON - IRON THERMOILEKTRIKI ANONYMI ETAIREIA</b>',
				'GDPR_CHAPTER_2BJ_EMAIL':'Sähköposti: tietosuojavastaava: herondpo@gr.andersenlegal.com  / yhteyshenkilöt: apapakonstantinou@heron.gr; mparaschi@heron.gr; rnd@heron.gr',
				'GDPR_CHAPTER_2BK':'<b>OPTIMUS ENERGY</b>',
				'GDPR_CHAPTER_2BK_EMAIL':'Sähköposti: csimoglou@optimusenergy.gr ; dchatzigiannis@optimusenergy.gr (yhteyshenkilöt)',
				'GDPR_CHAPTER_2BL':'<b>Zveza potrošnikov Slovenije (ZPS)</b>',
				'GDPR_CHAPTER_2BL_EMAIL':'Sähköposti: Maja Lubarda (maja.lubarda@gmail.com)',
				'GDPR_CHAPTER_3':'3. Yhteisrekisterin osalta rekisterinpitäjien vastuunjako',
				'GDPR_CHAPTER_3A':'Teknologian Tutkimuskeskus VTT Oy on ensisijainen rekisteröityjen yhteystaho ja koordinoi muiden yhteisrekisterinpitäjien suuntaan rekisteröityjen pyyntöjä. Muut yhteisrekisterinpitäjät (katso kohta 2) vastaavat omalta osaltaan pyyntöjen toteuttamisesta. Rekisteröity voi toteuttaa henkilötietojen käsittelyä koskevat oikeutensa keskitetysti yhteyshenkilön välityksellä: Seppo Viinikainen, Teknologian tutkimuskeskus VTT Oy, Koivurannantie 1, 40400 Jyväskylä, <a href="mailto:Seppo.Viinikainen@vtt.fi">Seppo.Viinikainen@vtt.fi</a>. Yhteyshenkilö toimittaa tarvittaessa rekisteröidyn yhteydenoton muille yhteisrekisterinpitäjille.',
				'GDPR_CHAPTER_4':'4. Käsiteltävät henkilötiedot',
				'GDPR_CHAPTER_4A':'Käsiteltävät henkilötiedot ovat: Asunnon lämpötila, kosteus, CO2, VOC-yhdisteet, käyttäjäpalaute, käyttäjän sähköpostiosoite, asunnon numero.',
				'GDPR_CHAPTER_4B':'Henkilöt edustavat seuraavia ryhmiä: HOAS-opiskelija-asunnossa asuvia tutkimukseen osallistuvia henkilöitä.',
				'GDPR_CHAPTER_5':'5. Käsittelytarkoitus ja oikeusperuste',
				'GDPR_CHAPTER_5A':'Henkilötietojen käsittelyn tarkoitus on: VTT käsittelee kerättyjä tietoja suostumuksellasi projektissa tehtävään energia-aiheiseen tutkimukseen asuntojen olosuhteista ja energiankulutuksesta. Tietoja käytetään ainoastaan tutkimustarkoituksiin.',
				'GDPR_CHAPTER_5B':'Henkilötietojen käsittelyn oikeusperuste<sup>1</sup>:',
				'GDPR_CHAPTER_5BA':'Yleistä etua koskeva tehtävä',
				'GDPR_CHAPTER_5BAA':'tieteellinen tai historiallinen tutkimus tai tilastointi',
				'GDPR_CHAPTER_5BAB':'tutkimusaineistojen ja kulttuuriperintöaineistojen arkistointi',
				'GDPR_CHAPTER_5BB':'Rekisterinpitäjän tai kolmannen osapuolen oikeutettujen etujen toteuttaminen',
				'GDPR_CHAPTER_5BBA':'mikä oikeutettu etu on kyseessä:',
				'GDPR_CHAPTER_5BC':'Rekisteröidyn suostumus',
				'GDPR_CHAPTER_5BD':'Muu:',
				'GDPR_CHAPTER_5B_SUP':'<sup>1</sup>Tietosuoja-asetus, artikla 6 ja tietosuojalaki 4 §.',
				'GDPR_CHAPTER_6':'6. Henkilötietojen tietolähteet',
				'GDPR_CHAPTER_6A':'Tiedot saadaan keräämällä mittauslaitteilla ja sensoreilla asunnosta olosuhteisiin ja energiankulutukseen liittyviä tietoja. Lisäksi asukkaan on mahdollista antaa palautetta myös asukkaan käyttöliittymän kautta.',
				'GDPR_CHAPTER_7':'7. Henkilötietojen vastaanottajat tai vastaanottajaryhmät',
				'GDPR_CHAPTER_7A':'Henkilötietoja luovutetaan seuraaville vastaanottajille:',
				'GDPR_CHAPTER_7AA':'<b>Smart Com d.o.o.</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AB':'<b>Enerim Oy</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AC':'<b>Jozef Stefan Institute</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AD':'<b>ATHENS UNIVERSITY OF ECONOMICS AND BUSINESS</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AE':'<b>Intracom SA Telecom Solutions</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AF':'<b>ELEKTRO CELJE</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AG':'<b>Caverion Oyj</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AH':'<b>In-JeT ApS</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AI':'<b>ECE d.o.o.</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AJ':'<b>HERON - IRON THERMOILEKTRIKI ANONYMI ETAIREIA</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AK':'<b>OPTIMUS ENERGY</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AL':'<b>Zveza potrošnikov Slovenije</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AM':'<b>Helsingin seudun opiskelija-asuntosäätiö HOAS</b> - henkilötietojen vastaanottaja',
				'GDPR_CHAPTER_8':'8. Henkilötietojen siirto EU:n tai ETA:n ulkopuolelle',
				'GDPR_CHAPTER_8A':'Henkilötietoja siirretään EU:n/ ETA:n ulkopuolelle (huomioiden palvelimien sijainti ja myös pääsyoikeudet):',
				'GDPR_CHAPTER_8AA':'Ei',
				'GDPR_CHAPTER_8AB':'Mahdollista, mekanismi täsmentyy ja informoidaan tapauskohtaisesti.',
				'GDPR_CHAPTER_8AC':'Kyllä, seuraavilla tietosuoja-asetuksen mukaisilla menettelyillä: ',
				'GDPR_CHAPTER_8BA':'Tietosuojan riittävyyttä koskeva komission päätös.',
				'GDPR_CHAPTER_8BB':'Yritystä koskevat sitovat säännöt ',
				'GDPR_CHAPTER_8BC':'Komission mallisopimuslausekkeet.',
				'GDPR_CHAPTER_8BD':'Muu:',
				'GDPR_CHAPTER_8BE':'Tiedossa olevat maat:',
				'GDPR_CHAPTER_9':'9. Automaattinen päätöksenteko',
				'GDPR_CHAPTER_9A':'Automaattista päätöksentekoa ei henkilötiedoista tehdä.',
				'GDPR_CHAPTER_10':'10. Henkilötietojen säilyttäminen',
				'GDPR_CHAPTER_10A':'Tutkimusaineisto ja sen mukana henkilötiedot hävitetään tutkimuksen päätyttyä.',
				'GDPR_CHAPTER_10B':'Tutkimuksen päätyttyä tutkimusaineisto säilytetään 24 kuukauden ajan, ja',
				'GDPR_CHAPTER_10BA':'henkilötiedot anonymisoidaan',
				'GDPR_CHAPTER_10BB':'henkilötiedot pseudonymisoidaan',
				'GDPR_CHAPTER_10BC':'aineisto sisältää suoria rekisteröidyn tunnistetietoja, peruste:',
				'GDPR_CHAPTER_10C':'Tutkimusaineisto tallennetaan tutkimuksen päätyttyä VTT:n palvelimella ylläpidettävässä tietokannassa.',
				'GDPR_CHAPTER_11':'11. Henkilötietojen suojauksen periaatteet',
				'GDPR_CHAPTER_11A':'Tutkimuksen suorittamista varten tutkimusaineisto:',
				'GDPR_CHAPTER_11AA':'anonymisoidaan ennen tutkimuksen aloittamista',
				'GDPR_CHAPTER_11AB':'pseudonymisoidaan',
				'GDPR_CHAPTER_11AC':'käsitellään rekisteröidyn suorin tunnistetiedoin.',
				'GDPR_CHAPTER_11B':'<b>Manuaalisesti</b> käsiteltävien henkilötietojen suojaaminen: Henkilötiedot pseudonymisoidaan ja suojataan VTT:n tutkimusympäristön käytäntöjen mukaisesti.',
				'GDPR_CHAPTER_11C':'<b>Tietojärjestelmässä</b> käsiteltävien henkilötietojen suojaaminen:',
				'GDPR_CHAPTER_11CA':'käyttäjätunnus',
				'GDPR_CHAPTER_11CB':'salasana',
				'GDPR_CHAPTER_11CC':'kaksivaiheinen käyttäjän tunnistus (MFA)',
				'GDPR_CHAPTER_11CD':'pääsynhallinta verkko-osoitteiden avulla (IP-osoitteet)',
				'GDPR_CHAPTER_11CE':'käytön rekisteröinti (lokitietojen kerääminen)',
				'GDPR_CHAPTER_11CF':'kulunvalvonta',
				'GDPR_CHAPTER_11D':'<b>Tiedonsiirrossa</b> henkilötietojen suojaaminen:',
				'GDPR_CHAPTER_11DA':'tiedonsiirron salaus: HTTPS-standardi, SSL-protokolla',
				'GDPR_CHAPTER_11DB':'tiedoston salaus: Käyttäjätunnus ja salasana',
				'GDPR_CHAPTER_11DC':'muu, mikä:',
				'GDPR_CHAPTER_12':'12. Rekisteröidyn oikeudet',
				'GDPR_CHAPTER_12A':'Rekisteröidyllä on seuraavat oikeudet, joista kuitenkin voidaan poiketa ja/tai joita voidaan rajoittaa soveltuvan lainsäädännön mukaisesti. Rajoittaminen ja poikkeaminen tarkistetaan tapauskohtaisesti.',
				'GDPR_CHAPTER_12B':'Lisätietoja rekisteröidyn oikeuksista:',
				'GDPR_CHAPTER_12C':'<b>Oikeus peruuttaa suostumuksensa</b>',
				'GDPR_CHAPTER_12CA':'Mikäli käsittely perustuu suostumukseen, rekisteröidyllä on milloin tahansa oikeus peruuttaa suostumuksensa henkilötietojensa käsittelyä koskien.',
				'GDPR_CHAPTER_12D':'<b>Rekisteröidyn oikeus saada pääsy tietoihin</b>',
				'GDPR_CHAPTER_12DA':'Rekisteröidyllä on oikeus saada rekisterinpitäjältä vahvistus siitä, käsitelläänkö häntä koskevia henkilötietoja. Rekisteröidyllä on lisäksi oikeus saada pääsy rekisteröityä itseään koskeviin henkilötietoihin sekä tiedot henkilötietojen käsittelystä.',
				'GDPR_CHAPTER_12E':'<b>Oikeus tietojen oikaisemiseen</b>',
				'GDPR_CHAPTER_12EA':'Rekisteröidyllä on oikeus saada rekisteröityä koskevat epätarkat ja virheelliset henkilötiedot ilman aiheetonta viivytystä oikaistua ja puutteelliset henkilötiedot täydennettyä.',
				'GDPR_CHAPTER_12F':'<b>Oikeus tietojen poistamiseen, ns. "oikeus tulla unohdetuksi"</b>',
				'GDPR_CHAPTER_12FA':'Rekisteröidyllä on oikeus saada rekisterinpitäjä poistamaan rekisteröityä koskevat henkilötiedot ilman aiheetonta viivytystä.',
				'GDPR_CHAPTER_12G':'<b>Oikeus käsittelyn rajoittamiseen</b>',
				'GDPR_CHAPTER_12GA':'Rekisteröidyllä on tietyissä tilanteissa oikeus vaatia, että rekisterinpitäjä rajoittaa käsittelyä.',
				'GDPR_CHAPTER_12H':'<b>Oikeus siirtää tiedot järjestelmästä toiseen</b>',
				'GDPR_CHAPTER_12HA':'Rekisteröidyllä on oikeus saada häntä koskevat henkilötiedot, jotka hän on toimittanut rekisterinpitäjälle, ja oikeus siirtää kyseiset tiedot toiselle rekisterinpitäjälle siltä osin kuin käsittely perustuu suostumukseen tai sopimukseen, ja käsittely suoritetaan automaattisesti.',
				'GDPR_CHAPTER_12I':'<b>Oikeus tehdä valitus valvontaviranomaiselle</b>',
				'GDPR_CHAPTER_12IA':'Rekisteröidyllä on oikeus tehdä valitus valvontaviranomaisille, jos rekisteröity katsoo, että hänen oikeuksiaan on EU:n tietosuoja-asetuksen valossa loukattu. Tietosuojavaltuutetun yhteystiedot: <a href="https://tietosuoja.fi/yhteystiedot" target="_blank">https://tietosuoja.fi/yhteystiedot</a>',
				'GDPR_CHAPTER_12J':'<b>Rekisteröity voi toteuttaa yllämainitut oikeutensa ottamalla rekisterinpitäjään yhteyttä kohdassa 2 määriteltyjen yhteystietojen avulla, mieluiten sähköpostitse.</b>',
				'SESSION_EXPIRED':'Session has expired... logging out in 3 seconds!',
				'MENU_VERSION':'v 22.03.09-G'
			},
			'fi':{
				'USER_LOGIN_TITLE':'Kirjautuminen',
				'USER_EMAIL':'Sähköposti',
				'USER_PASSWORD':'Salasana',
				'USER_REGCODE':'Rekisteröintikoodi',
				'USER_LOGIN_BTN_TXT':'KIRJAUDU SISÄÄN',
				'USER_OPEN_SIGNUP_FORM':'Rekisteröityminen &raquo;',
				'USER_SIGNUP_TITLE':'Rekisteröityminen',
				'USER_SIGNUP_BTN_TXT':'Rekisteröidy',
				'USER_SIGNUP_TABLET_TXT':'Laita rasti alla olevaan ruutuun jos haluat tablettitietokoneen. Koska tabletteja on tässä kokeilussa rajoitettu määrä, toimi nopeasti.',
				'USER_SIGNUP_TABLET_CHECKBOX_LABEL':'Kyllä, haluan tabletin.',
				'USER_SIGNUP_CONSENT_OK_1':'Olen lukenut ',
				'USER_SIGNUP_GDPR_LINK_TXT':'tietosuojaselosteen',
				'USER_SIGNUP_CONSENT_OK_2':' ja annan suostumukseni ',
				'USER_SIGNUP_CONSENT_LINK_TXT':'suostumuslomakkeella.',
				'USER_SIGNUP_APARTMENT_ADDRESS':'Osoite',
				'USER_SIGNUP_APARTMENT_LETTER':'Rappu',
				'USER_SIGNUP_APARTMENT_NUMBER':'Numero',
				'USER_SIGNUP_APARTMENT_NOT_SELECTED':'Ei valittu',
				'USER_SIGNUP_APARTMENT_MUST_INPUT':'<b>Asunnon numero</b> täytyy ilmoittaa</b>',
				'HELP_INFO_TITLE':'Making City -kokeilu',
				'HELP_INFO_THANKS':'Kiitos. Olet rekisteröitynyt Making City -kokeiluun. Nyt voit kirjautua sisään.',
				'HELP_INFO_1':'Voit tarkastella <b>talokohtaisia</b> mittauksia ilman rekisteröitymistä tai kirjautumista.',
				'HELP_INFO_2':'Voit tarkastella <b>asuntoasi</b> koskevia mittauksia ja antaa <b>asuntoasi</b> koskevaa palautetta rekisteröitymällä ja kirjautumalla sisään.',
				'HELP_INFO_3':'',
				'HELP_INFO_4':'',
				'HELP_INFO_5':'',
				'COMING_SOON':'TULOSSA PIAN!',
				'USER_PAGE_ELECTRICITY':'Sähkö',
				'USER_PAGE_HEATING':'Lämmitys',
				'USER_PAGE_WATER':'Vesi',
				'GRID_PAGE_TITLE':'Sähköverkko',
				'GRID_PAGE_DESCRIPTION':'Täältä löytyy lisätietoa sähköverkon kuormituksesta (Fingridin avoin data). Kaikki lukuarvot päivittyvät 3 minuutin välein.',
				'GRID_PAGE_PRICE':'Hinta',
				'SOLAR_PAGE_TITLE':'Aurinkoenergia',
				'SOLAR_PAGE_DESCRIPTION':'Aurinkoenergian tuotantoennuste seuraaville 36 tunnille. Ennuste päivittyy tunnin välein.',
				'SOLAR_ENERGY':'Aurinkoenergia',
				'SOLAR_ENERGY_POWER':'Teho',
				'ENVIRONMENT_PAGE_TITLE':'Ympäristövaikutus',
				'ENVIRONMENT_PAGE_DESCRIPTION':'Täältä löytyy lisätietoa kulutetun energian vaikutuksesta ympäristöön.',
				'ENVIRONMENT_PAGE_AXIS_TITLE':'Päästöt gCO2/kWh',
				'ENVIRONMENT_PAGE_CONS_TOOLTIP':'Kulutus',
				'ENVIRONMENT_PAGE_PROD_TOOLTIP':'Tuotanto',
				'ENVIRONMENT_PAGE_CONS_LEGEND_LABEL':'Kulutus',
				'ENVIRONMENT_PAGE_PROD_LEGEND_LABEL':'Tuotanto',
				'ENVIRONMENT_PAGE_LATEST_CONSUMPTION':'Viimeisin kulutus',
				'ENVIRONMENT_PAGE_AVERAGE_CONSUMPTION':'Keskiarvo',
				'USER_PROPS_TITLE':'Omat tiedot',
				'USER_PROPS_DESCRIPTION':'Tällä sivulla käyttäjä voi katsoa ja muokata omia tietojaan.',
				'USER_ENERGY_PRICES_TITLE':'Energian hinta',
				'USER_ENERGY_PRICES_DESCRIPTION':'Syötä hinnat omasta sähkösopimuksestasi, niin voimme laskea sähkönkulutuksen jaksokohtaiset hinta-arviot.',
				'USER_ENERGY_PRICES_MONTHLY':'Kuukausimaksu: ',
				'USER_ENERGY_PRICES_MONTHLY_UNIT':'€/kk',
				'USER_ENERGY_PRICES_ENERGY':'Energiamaksu: ',
				'USER_ENERGY_PRICES_ENERGY_UNIT':'snt/kWh',
				'USER_ENERGY_PRICES_TRANSFER':'Siirtomaksu: ',
				'USER_ENERGY_PRICES_TRANSFER_UNIT':'snt/kWh',
				'USER_ENERGY_PRICE_SAVED_OK':'Uusi hinta talletettu.',
				'USER_PROPS_CONSENT':'Täältä voit lukea ',
				'USER_PROPS_ADMIN_DESCRIPTION':'Ylläpitäjä voi nähdä ja muokata rekisteröintikoodeja ja lisäksi hallita kaikkien käyttäjien lukuavaimia.',
				'USER_PROPS_ADMIN_REGCODES':'Rekisteröintikoodit',
				'USER_PROPS_ADMIN_REGCODES_CREATE_BTN_TXT':'Luo uusi',
				'USER_PROPS_ADMIN_USERS':'Käyttäjät',
				'USER_PROPS_ADMIN_CONFIGS':'Asetukset',
				'USER_PROPS_ADMIN_FEEDBACKS':'Palautteet',
				'USER_CONSENT_TXT':'Täältä voit katsella ',
				'USER_CONSENT_LINK_TXT':'suostumuslomakettasi.',
				'USER_GDPR_TXT':'Täältä voit lukea ',
				'USER_GDPR_LINK_TXT':'tietosuojaselosteen (GDPR).',
				'ADMIN_START_LABEL':'Alkaa',
				'ADMIN_END_LABEL':'Loppuu',
				'USER_PROPS_CHANGE_PASSWORD_BTN_TXT':'Vaihda salasanasi',
				'USER_CHANGE_PASSWORD_TITLE':'Salasanan vaihto',
				'USER_OLD_PASSWORD':'Vanha salasana',
				'USER_NEW_PASSWORD':'Uusi salasana',
				'USER_DATA_PERIOD':'Jakso',
				'USER_DATA_PERIOD_DAY':'24h',
				'USER_DATA_PERIOD_WEEK':'Viikko',
				'USER_DATA_PERIOD_MONTH':'Kuukausi',
				'USER_DATA_TARGET':'Tavoitearvo',
				'USER_DATA_UPPER_LIMIT':'Yläraja',
				'USER_DATA_LOWER_LIMIT':'Alaraja',
				'USER_DATA_WATER_HOT':'KUUMA (L)',
				'USER_DATA_WATER_COLD':'KYLMÄ (L)',
				'USER_ELECTRICITY_TITLE':'Asuntokohtainen sähkönkulutus',
				'USER_ELECTRICITY_DESCRIPTION':'Täältä löytyvät tiedot asuntokohtaisesta sähkönkulutuksesta.',
				'USER_ELECTRICITY_CHART_TITLE':'Sähkönkulutus',
				'USER_CHART_X_DAYS':'päivää',
				'USER_CHART_X_DAYS_WAIT':'Kulutustietoa ei vielä saatavilla... katso huomenna uudelleen.',
				'USER_ELECTRICITY_TARGETS_TITLE':'Tavoitearvot 24h sähkönkulutukselle',
				'USER_ELECTRICITY_TARGETS_DESCRIPTION':'Anna ylä- ja alarajat sekä tavoitearvot <b>yhden vuorokauden</b> sähkönkulutukselle.',
				'USER_TARGETS_ALARM_COUNT_DESCRIPTION':'Numerot kertovat viimeisten 30 päivän hälytysten lukumäärän annetuilla rajoilla laskettuna.',
				'USER_HEATING_TITLE':'Asuntokohtainen lämmitys',
				'USER_HEATING_DESCRIPTION':'Täältä löytyvät tiedot asuntokohtaisesta lämmityksestä.',
				'USER_HEATING_CHART_TITLE':'Lämpötila ja kosteus',
				'USER_HEATING_CHART_LEGEND_TEMPERATURE':'Lämpötila',
				'USER_HEATING_CHART_LEGEND_HUMIDITY':'Kosteus',
				'USER_HEATING_CHART_AVERAGE':'Keskiarvo',
				'USER_HEATING_FEEDBACK_PROMPT':'Anna palautetta: miltä asunnon lämpötila tuntuu tänään? Valitse hymiö ja lähetä palaute.',
				'USER_HEATING_SEND_FEEDBACK':'Lähetä palaute',
				'USER_HEATING_FEEDBACK_OK':'Kiitos palautteesta!',
				'USER_HEATING_TARGETS_TITLE':'Tavoitearvot lämmitykselle',
				'USER_HEATING_TARGETS_BOTH_DESCRIPTION':'Anna ylä- ja alarajat sekä tavoitearvot lämpötilalle ja kosteudelle.',
				'USER_TARGET':'Tavoite: ',
				'USER_UPPER_LIMIT':'Yläraja: ',
				'USER_LOWER_LIMIT':'Alaraja: ',
				'USER_TARGET_SAVED':'Uusi tavoite/raja talletettu.',
				'USER_WATER_TITLE':'Asuntokohtainen vedenkulutus',
				'USER_WATER_DESCRIPTION':'Täältä löytyvät tiedot asuntokohtaisesta vedenkulutuksesta',
				'USER_WATER_CHART_TITLE':'Vedenkulutus',
				'USER_WATER_CHART_TITLE_30_DAYS':'Vedenkulutus 30 päivää',
				'USER_WATER_CHART_LEGEND_HOT':'Kuuma',
				'USER_WATER_CHART_LEGEND_COLD':'Kylmä',
				'USER_WATER_TARGETS_TITLE':'Tavoitearvot 24h vedenkulutukselle',
				'USER_WATER_TARGETS_BOTH_DESCRIPTION':'Anna ylä- ja alarajat sekä tavoitearvot <b>yhden vuorokauden</b> vedenkulutukselle.',
				'USER_ALARM_TITLE':'Hälytykset',
				'USER_ALARM_DESCRIPTION':'Täältä voit seurata mitä hälytyksiä tai muita hyödyllisiä viestejä systeemi on generoinut.',
				'USER_ALARM_CHART_TITLE':'Lukumäärä',
				'USER_ALARM_VIEW_TABLE_HEADER_TYPE':'Tyyppi',
				'USER_ALARM_VIEW_TABLE_HEADER_COUNT':'Lukumäärä',
				'USER_ALARM_VIEW_TABLE_HEADER_DETAILS':'&nbsp;',
				'USER_ALARM_VIEW_HEATING_TEMPERATURE_UPPER_LIMIT':'Lämpötilan yläraja',
				'USER_ALARM_VIEW_HEATING_TEMPERATURE_LOWER_LIMIT':'Lämpötilan alaraja',
				'USER_ALARM_VIEW_HEATING_HUMIDITY_UPPER_LIMIT':'Kosteuden yläraja',
				'USER_ALARM_VIEW_HEATING_HUMIDITY_LOWER_LIMIT':'Kosteuden alaraja',
				'USER_ALARM_VIEW_WATER_HOT_UPPER_LIMIT':'Kuuman veden yläraja',
				'USER_ALARM_VIEW_WATER_HOT_LOWER_LIMIT':'Kuuman veden alaraja',
				'USER_ALARM_VIEW_WATER_COLD_UPPER_LIMIT':'Kylmän veden yläraja',
				'USER_ALARM_VIEW_WATER_COLD_LOWER_LIMIT':'Kylmän veden alaraja',
				'USER_ALARM_VIEW_ENERGY_UPPER_LIMIT':'Sähkönkulutuksen yläraja',
				'USER_ALARM_VIEW_ENERGY_LOWER_LIMIT':'Sähkönkulutuksen alaraja',
				'USER_ALARM_DETAILS_DESCRIPTION':'Hälytysten päiväkohtainen lukumäärä kuukauden ajalta',
				'DISTRICT_A_LABEL':'S-Arina',
				'DISTRICT_B_LABEL':'Sivakka 1',
				'DISTRICT_C_LABEL':'Sivakka 2',
				'DISTRICT_D_LABEL':'Koulu',
				'DISTRICT_E_LABEL':'Sivakka 3',
				'DISTRICT_F_LABEL':'YIT 1',
				'MENU_TITLE':'Energiataseeltaan positiivinen alue',
				'MENU_DESCRIPTION':'<a href="http://makingcity.eu/" target="_blank" rel="noreferrer noopener" aria-label="This is an external link (opens in a new tab)">MAKING-CITY HANKE</a> saa rahoitusta EU:n Horizon 2020 -ohjelmasta. Se kuuluu Smart Cities and Communities (SCC) -teemaan.',
				'MENU_VISIT_COUNT':'kävijälaskuri',
				'SOLAR_PANELS':'AURINKOPANEELIT',
				'GRID_TEXT':'SÄHKÖVERKKO',
				'DA_BACK':'TAKAISIN',
				'DA_CANCEL':'PERU',
				'DA_SAVE':'TALLETA',
				'DAA_TITLE':'Grid',
				'DAB_TITLE':'Aurinkoteho',
				'DAC_TITLE':'Valaistus ja laitteet',
				'DAD_TITLE':'Keittiön laitteet',
				'DAE_TITLE':'LVI',
				'DAF_TITLE':'Muut',
				'DAG_TITLE':'Kompressorit, kylmälaitteet ja lämmitys',
				'DAHA_TITLE':'Kompressorit',
				'DAP_TITLE_A':'Kauko-',
				'DAP_TITLE_B':'lämpö-',
				'DAP_TITLE_C':'verkko',
				'DAHB_TITLE':'Kylmälaitteet',
				'DAHC_TITLE':'Jäähdytys',
				'DAHD_TITLE':'Lämmitys',
				'DAI_TITLE':'Maalämpö',
				'DAA_POWER':'Teho',
				'DAA_ENERGY':'Energia',
				'DAW_SEL_TIMERANGE':'Valitse kuvaajan aikaikkuna:',
				'DBA_TITLE':'Grid',
				'DBB_TITLE':'Aurinkoenergia',
				'DBD_TITLE':'Asunnot',
				'DBE_TITLE_1':'SAUNA,',
				'DBE_TITLE_2':'valot,',
				'DBE_TITLE_3':'yms.',
				'DBF_TITLE_1':'Heating',
				'DBF_TITLE_2':'system',
				'DBG_TITLE_1':'Exthaus air',
				'DBG_TITLE_2':'recovery',
				'DBH_TITLE_1':'Wastewater',
				'DBH_TITLE_2':'recovery',
				'DBI_TITLE_1':'Kauko-',
				'DBI_TITLE_2':'lämpö-',
				'DBI_TITLE_3':'verkko',
				'DBJ_TITLE_1':'Heating',
				'DBJ_TITLE_2':'devices',
				'DBK_TITLE_1':'Kuuma',
				'DBK_TITLE_2':'vesi',
				'ADMIN_EDIT_POINT_ID_TITLE':'PointId koodi',
				'ADMIN_EDIT_POINT_ID_DESCRIPTION':'Voit muuttaa käyttäjän PointId koodia',
				'ADMIN_EDIT_POINT_ID_LABEL':'PointId koodi',
				'CANCEL':'&nbsp;PERU&nbsp;',
				'SAVE':'TALLETA',
				'UPDATE':'PÄIVITÄ',
				'BACK':'TAKAISIN',
				'OK':'&nbsp;&nbsp;&nbsp;&nbsp;OK&nbsp;&nbsp;&nbsp;&nbsp;',
				'AUTO_UPDATE_MSG_1':'Kuvaaja päivittyy automaattisesti kerran',
				'AUTO_UPDATE_MSG_1_B':'Teholukemat päivittyvät automaattisesti kerran',
				'AUTO_UPDATE_MSG_2':'sekunnissa',
				'AUTO_UPDATE_MSG_3':'Kuvaaja EI päivity automaattisesti',
				'ADJUST_UPDATE_INTERVAL':'Säädä päivitystaajuutta (0-60s):',
				'UPDATED_HEADER_TEXT':'Luvut päivitetty: ',
				'CONSENT_TITLE':'SUOSTUMUS',
				'CONSENT_TEXT_A':'Vahvistan lukeneeni ja ymmärtäneeni tutkimustiedotteen ja sen liitteenä olleen tietosuojailmoituksen. Vahvistan, että tiedossani ei ole tutkimustiedotteessa esitettyä poissulkukriteeriä ja/tai täytän valintakriteerit. Minulla on ollut mahdollisuus harkita saamaani tietoa, esittää kysymyksiä ja olen saanut kysymyksiini riittävän vastauksen.',
				'CONSENT_CHECK_A':'Annan suostumukseni <b>tutkimukseen osallistumiseen</b>. Minulla on oikeus keskeyttää osallistuminen väliaikaisesti tai toistaiseksi (jättäytyä tutkimuksen vaiheen ulkopuolelle) tai peruuttaa suostumus, milloin tahansa ilman erityistä syytä ja syytä kertomatta.',
				'CONSENT_CHECK_B':'Annan suostumukseni <b>henkilötietojen käsittelyyn tutkimuksessa</b>. Minulla on oikeus, milloin tahansa perua suostumukseni ilman erityistä syytä ja syytä kertomatta.',
				'CONSENT_TEXT_B':'Voin perua yllä olevan suostumukseni, mutta ymmärrän aineiston julkiseksi saattamisen jälkeen poistamisen rajoitteet.',
				'GDPR_TITLE':'Tietosuojailmoitus tutkimukseen',
				'GDPR_DESCRIPTION':'Tietosuojailmoitus perustuu EU:n yleiseen tietosuoja-asetukseen (2016/679, "tietosuoja-asetus") ja tietosuojalakiin (1050/2018).',
				'GDPR_CHAPTER_1':'1. Tutkimuksen nimi ja kesto',
				'GDPR_CHAPTER_1A':'Tutkimuksen nimi: iFLEX (Intelligent Assistants for Flexibility Management',
				'GDPR_CHAPTER_1B':'Tutkimuksen kestoaika: 1.11.2020 - 31.10.2023',
				'GDPR_CHAPTER_2':'2. Rekisterinpitäjä(-t), tietosuojavastaava ja yhteyshenkilö(-t)',
				'GDPR_CHAPTER_2A':'Teknologian Tutkimuskeskus VTT Oy (”VTT”), Y-tunnus: 2647375-4, Vuorimiehentie 3, 02150 Espoo',
				'GDPR_CHAPTER_2AA':'Tietosuojavastaava:',
				'GDPR_CHAPTER_2AAA':'Nimi: Seppo Viinikainen',
				'GDPR_CHAPTER_2AAB':'Osoite: Teknologian tutkimuskeskus VTT Oy, Koivurannantie 1, 40400 Jyväskylä',
				'GDPR_CHAPTER_2AAC':'Sähköposti: <a href="mailto:Seppo.Viinikainen@vtt.fi">Seppo.Viinikainen@vtt.fi</a> (tietosuojavastaava) tai <a href="mailto:tietosuoja@vtt.fi">tietosuoja@vtt.fi</a> (tietosuojavastaava, tietoturvapäällikkö, HR ja lakimies)',
				'GDPR_CHAPTER_2AB':'Tutkimuksesta vastaavan yhteyshenkilön tai tutkimusryhmän yhteystiedot:',
				'GDPR_CHAPTER_2ABA':'Nimi: Markus Taumberger, Jussi Kiljander, Anne Immonen',
				'GDPR_CHAPTER_2ABB':'Osoite: Teknologian tutkimuskeskus VTT Oy, Kaitoväylä 1, 90571 Oulu',
				'GDPR_CHAPTER_2ABC':'Sähköposti: <a href="mailto:iFLEX-Info@vtt.fi">iFLEX-Info@vtt.fi</a>',
				'GDPR_CHAPTER_2B':'Muut yhteisrekisterinpitäjät:',
				'GDPR_CHAPTER_2BA':'<b>Smart Com d.o.o.</b>',
				'GDPR_CHAPTER_2BA_EMAIL':'Sähköposti: skrbnikVOP@smart-com.si',
				'GDPR_CHAPTER_2BB':'<b>Enerim Oy</b>',
				'GDPR_CHAPTER_2BB_EMAIL':'Sähköposti: heikki.hiltunen@enerim.com',
				'GDPR_CHAPTER_2BC':'<b>Jozef Stefan Institute</b>',
				'GDPR_CHAPTER_2BC_EMAIL':'Sähköposti: dusan.gabrijelcic@jsi.si',
				'GDPR_CHAPTER_2BD':'<b>ATHENS UNIVERSITY OF ECONOMICS AND BUSINESS (AUEB)</b>',
				'GDPR_CHAPTER_2BD_EMAIL':'Sähköposti: Maria Antonopoulou, dpo@aueb.gr yhteyshenkilö: Stamoulis George, gstamoul@aueb.gr',
				'GDPR_CHAPTER_2BE':'<b>Intracom SA Telecom Solutions</b>',
				'GDPR_CHAPTER_2BE_EMAIL':'Sähköposti: labil@intracom-telecom.com (yhteyshenkilö)',
				'GDPR_CHAPTER_2BF':'<b>ELEKTRO CELJE, podjetje za distribucijo električne energije, d.d.</b>',
				'GDPR_CHAPTER_2BF_EMAIL':'Sähköposti: anton.kos@elektro-celje.si; mojca.potecin@elektro-celje.si',
				'GDPR_CHAPTER_2BG':'<b>Caverion Oyj</b>',
				'GDPR_CHAPTER_2BG_EMAIL':'Sähköposti: olli.nummelin@caverion.com',
				'GDPR_CHAPTER_2BH':'<b>In-JeT ApS</b>',
				'GDPR_CHAPTER_2BH_EMAIL':'Sähköposti: tfs@in-jet.dk',
				'GDPR_CHAPTER_2BI':'<b>ECE d.o.o.</b>',
				'GDPR_CHAPTER_2BI_EMAIL':'Sähköposti: gasper.ravnak@ece.si ; andraz.javernik@ece.si',
				'GDPR_CHAPTER_2BJ':'<b>HERON - IRON THERMOILEKTRIKI ANONYMI ETAIREIA</b>',
				'GDPR_CHAPTER_2BJ_EMAIL':'Sähköposti: tietosuojavastaava: herondpo@gr.andersenlegal.com  / yhteyshenkilöt: apapakonstantinou@heron.gr; mparaschi@heron.gr; rnd@heron.gr',
				'GDPR_CHAPTER_2BK':'<b>OPTIMUS ENERGY</b>',
				'GDPR_CHAPTER_2BK_EMAIL':'Sähköposti: csimoglou@optimusenergy.gr ; dchatzigiannis@optimusenergy.gr (yhteyshenkilöt)',
				'GDPR_CHAPTER_2BL':'<b>Zveza potrošnikov Slovenije (ZPS)</b>',
				'GDPR_CHAPTER_2BL_EMAIL':'Sähköposti: Maja Lubarda (maja.lubarda@gmail.com)',
				'GDPR_CHAPTER_3':'3. Yhteisrekisterin osalta rekisterinpitäjien vastuunjako',
				'GDPR_CHAPTER_3A':'Teknologian Tutkimuskeskus VTT Oy on ensisijainen rekisteröityjen yhteystaho ja koordinoi muiden yhteisrekisterinpitäjien suuntaan rekisteröityjen pyyntöjä. Muut yhteisrekisterinpitäjät (katso kohta 2) vastaavat omalta osaltaan pyyntöjen toteuttamisesta. Rekisteröity voi toteuttaa henkilötietojen käsittelyä koskevat oikeutensa keskitetysti yhteyshenkilön välityksellä: Seppo Viinikainen, Teknologian tutkimuskeskus VTT Oy, Koivurannantie 1, 40400 Jyväskylä, <a href="mailto:Seppo.Viinikainen@vtt.fi">Seppo.Viinikainen@vtt.fi</a>. Yhteyshenkilö toimittaa tarvittaessa rekisteröidyn yhteydenoton muille yhteisrekisterinpitäjille.',
				'GDPR_CHAPTER_4':'4. Käsiteltävät henkilötiedot',
				'GDPR_CHAPTER_4A':'Käsiteltävät henkilötiedot ovat: Asunnon lämpötila, kosteus, CO2, VOC-yhdisteet, käyttäjäpalaute, käyttäjän sähköpostiosoite, asunnon numero.',
				'GDPR_CHAPTER_4B':'Henkilöt edustavat seuraavia ryhmiä: HOAS-opiskelija-asunnossa asuvia tutkimukseen osallistuvia henkilöitä.',
				'GDPR_CHAPTER_5':'5. Käsittelytarkoitus ja oikeusperuste',
				'GDPR_CHAPTER_5A':'Henkilötietojen käsittelyn tarkoitus on: VTT käsittelee kerättyjä tietoja suostumuksellasi projektissa tehtävään energia-aiheiseen tutkimukseen asuntojen olosuhteista ja energiankulutuksesta. Tietoja käytetään ainoastaan tutkimustarkoituksiin.',
				'GDPR_CHAPTER_5B':'Henkilötietojen käsittelyn oikeusperuste<sup>1</sup>:',
				'GDPR_CHAPTER_5BA':'Yleistä etua koskeva tehtävä',
				'GDPR_CHAPTER_5BAA':'tieteellinen tai historiallinen tutkimus tai tilastointi',
				'GDPR_CHAPTER_5BAB':'tutkimusaineistojen ja kulttuuriperintöaineistojen arkistointi',
				'GDPR_CHAPTER_5BB':'Rekisterinpitäjän tai kolmannen osapuolen oikeutettujen etujen toteuttaminen',
				'GDPR_CHAPTER_5BBA':'mikä oikeutettu etu on kyseessä:',
				'GDPR_CHAPTER_5BC':'Rekisteröidyn suostumus',
				'GDPR_CHAPTER_5BD':'Muu:',
				'GDPR_CHAPTER_5B_SUP':'<sup>1</sup>Tietosuoja-asetus, artikla 6 ja tietosuojalaki 4 §.',
				'GDPR_CHAPTER_6':'6. Henkilötietojen tietolähteet',
				'GDPR_CHAPTER_6A':'Tiedot saadaan keräämällä mittauslaitteilla ja sensoreilla asunnosta olosuhteisiin ja energiankulutukseen liittyviä tietoja. Lisäksi asukkaan on mahdollista antaa palautetta myös asukkaan käyttöliittymän kautta.',
				'GDPR_CHAPTER_7':'7. Henkilötietojen vastaanottajat tai vastaanottajaryhmät',
				'GDPR_CHAPTER_7A':'Henkilötietoja luovutetaan seuraaville vastaanottajille:',
				'GDPR_CHAPTER_7AA':'<b>Smart Com d.o.o.</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AB':'<b>Enerim Oy</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AC':'<b>Jozef Stefan Institute</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AD':'<b>ATHENS UNIVERSITY OF ECONOMICS AND BUSINESS</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AE':'<b>Intracom SA Telecom Solutions</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AF':'<b>ELEKTRO CELJE</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AG':'<b>Caverion Oyj</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AH':'<b>In-JeT ApS</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AI':'<b>ECE d.o.o.</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AJ':'<b>HERON - IRON THERMOILEKTRIKI ANONYMI ETAIREIA</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AK':'<b>OPTIMUS ENERGY</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AL':'<b>Zveza potrošnikov Slovenije</b> - yhteisrekisterinpitäjä, henkilötietojen käsittelijä',
				'GDPR_CHAPTER_7AM':'<b>Helsingin seudun opiskelija-asuntosäätiö HOAS</b> - henkilötietojen vastaanottaja',
				'GDPR_CHAPTER_8':'8. Henkilötietojen siirto EU:n tai ETA:n ulkopuolelle',
				'GDPR_CHAPTER_8A':'Henkilötietoja siirretään EU:n/ ETA:n ulkopuolelle (huomioiden palvelimien sijainti ja myös pääsyoikeudet):',
				'GDPR_CHAPTER_8AA':'Ei',
				'GDPR_CHAPTER_8AB':'Mahdollista, mekanismi täsmentyy ja informoidaan tapauskohtaisesti.',
				'GDPR_CHAPTER_8AC':'Kyllä, seuraavilla tietosuoja-asetuksen mukaisilla menettelyillä: ',
				'GDPR_CHAPTER_8BA':'Tietosuojan riittävyyttä koskeva komission päätös.',
				'GDPR_CHAPTER_8BB':'Yritystä koskevat sitovat säännöt ',
				'GDPR_CHAPTER_8BC':'Komission mallisopimuslausekkeet.',
				'GDPR_CHAPTER_8BD':'Muu:',
				'GDPR_CHAPTER_8BE':'Tiedossa olevat maat:',
				'GDPR_CHAPTER_9':'9. Automaattinen päätöksenteko',
				'GDPR_CHAPTER_9A':'Automaattista päätöksentekoa ei henkilötiedoista tehdä.',
				'GDPR_CHAPTER_10':'10. Henkilötietojen säilyttäminen',
				'GDPR_CHAPTER_10A':'Tutkimusaineisto ja sen mukana henkilötiedot hävitetään tutkimuksen päätyttyä.',
				'GDPR_CHAPTER_10B':'Tutkimuksen päätyttyä tutkimusaineisto säilytetään 24 kuukauden ajan, ja',
				'GDPR_CHAPTER_10BA':'henkilötiedot anonymisoidaan',
				'GDPR_CHAPTER_10BB':'henkilötiedot pseudonymisoidaan',
				'GDPR_CHAPTER_10BC':'aineisto sisältää suoria rekisteröidyn tunnistetietoja, peruste:',
				'GDPR_CHAPTER_10C':'Tutkimusaineisto tallennetaan tutkimuksen päätyttyä VTT:n palvelimella ylläpidettävässä tietokannassa.',
				'GDPR_CHAPTER_11':'11. Henkilötietojen suojauksen periaatteet',
				'GDPR_CHAPTER_11A':'Tutkimuksen suorittamista varten tutkimusaineisto:',
				'GDPR_CHAPTER_11AA':'anonymisoidaan ennen tutkimuksen aloittamista',
				'GDPR_CHAPTER_11AB':'pseudonymisoidaan',
				'GDPR_CHAPTER_11AC':'käsitellään rekisteröidyn suorin tunnistetiedoin.',
				'GDPR_CHAPTER_11B':'<b>Manuaalisesti</b> käsiteltävien henkilötietojen suojaaminen: Henkilötiedot pseudonymisoidaan ja suojataan VTT:n tutkimusympäristön käytäntöjen mukaisesti.',
				'GDPR_CHAPTER_11C':'<b>Tietojärjestelmässä</b> käsiteltävien henkilötietojen suojaaminen:',
				'GDPR_CHAPTER_11CA':'käyttäjätunnus',
				'GDPR_CHAPTER_11CB':'salasana',
				'GDPR_CHAPTER_11CC':'kaksivaiheinen käyttäjän tunnistus (MFA)',
				'GDPR_CHAPTER_11CD':'pääsynhallinta verkko-osoitteiden avulla (IP-osoitteet)',
				'GDPR_CHAPTER_11CE':'käytön rekisteröinti (lokitietojen kerääminen)',
				'GDPR_CHAPTER_11CF':'kulunvalvonta',
				'GDPR_CHAPTER_11D':'<b>Tiedonsiirrossa</b> henkilötietojen suojaaminen:',
				'GDPR_CHAPTER_11DA':'tiedonsiirron salaus: HTTPS-standardi, SSL-protokolla',
				'GDPR_CHAPTER_11DB':'tiedoston salaus: Käyttäjätunnus ja salasana',
				'GDPR_CHAPTER_11DC':'muu, mikä:',
				'GDPR_CHAPTER_12':'12. Rekisteröidyn oikeudet',
				'GDPR_CHAPTER_12A':'Rekisteröidyllä on seuraavat oikeudet, joista kuitenkin voidaan poiketa ja/tai joita voidaan rajoittaa soveltuvan lainsäädännön mukaisesti. Rajoittaminen ja poikkeaminen tarkistetaan tapauskohtaisesti.',
				'GDPR_CHAPTER_12B':'Lisätietoja rekisteröidyn oikeuksista:',
				'GDPR_CHAPTER_12C':'<b>Oikeus peruuttaa suostumuksensa</b>',
				'GDPR_CHAPTER_12CA':'Mikäli käsittely perustuu suostumukseen, rekisteröidyllä on milloin tahansa oikeus peruuttaa suostumuksensa henkilötietojensa käsittelyä koskien.',
				'GDPR_CHAPTER_12D':'<b>Rekisteröidyn oikeus saada pääsy tietoihin</b>',
				'GDPR_CHAPTER_12DA':'Rekisteröidyllä on oikeus saada rekisterinpitäjältä vahvistus siitä, käsitelläänkö häntä koskevia henkilötietoja. Rekisteröidyllä on lisäksi oikeus saada pääsy rekisteröityä itseään koskeviin henkilötietoihin sekä tiedot henkilötietojen käsittelystä.',
				'GDPR_CHAPTER_12E':'<b>Oikeus tietojen oikaisemiseen</b>',
				'GDPR_CHAPTER_12EA':'Rekisteröidyllä on oikeus saada rekisteröityä koskevat epätarkat ja virheelliset henkilötiedot ilman aiheetonta viivytystä oikaistua ja puutteelliset henkilötiedot täydennettyä.',
				'GDPR_CHAPTER_12F':'<b>Oikeus tietojen poistamiseen, ns. "oikeus tulla unohdetuksi"</b>',
				'GDPR_CHAPTER_12FA':'Rekisteröidyllä on oikeus saada rekisterinpitäjä poistamaan rekisteröityä koskevat henkilötiedot ilman aiheetonta viivytystä.',
				'GDPR_CHAPTER_12G':'<b>Oikeus käsittelyn rajoittamiseen</b>',
				'GDPR_CHAPTER_12GA':'Rekisteröidyllä on tietyissä tilanteissa oikeus vaatia, että rekisterinpitäjä rajoittaa käsittelyä.',
				'GDPR_CHAPTER_12H':'<b>Oikeus siirtää tiedot järjestelmästä toiseen</b>',
				'GDPR_CHAPTER_12HA':'Rekisteröidyllä on oikeus saada häntä koskevat henkilötiedot, jotka hän on toimittanut rekisterinpitäjälle, ja oikeus siirtää kyseiset tiedot toiselle rekisterinpitäjälle siltä osin kuin käsittely perustuu suostumukseen tai sopimukseen, ja käsittely suoritetaan automaattisesti.',
				'GDPR_CHAPTER_12I':'<b>Oikeus tehdä valitus valvontaviranomaiselle</b>',
				'GDPR_CHAPTER_12IA':'Rekisteröidyllä on oikeus tehdä valitus valvontaviranomaisille, jos rekisteröity katsoo, että hänen oikeuksiaan on EU:n tietosuoja-asetuksen valossa loukattu. Tietosuojavaltuutetun yhteystiedot: <a href="https://tietosuoja.fi/yhteystiedot" target="_blank">https://tietosuoja.fi/yhteystiedot</a>',
				'GDPR_CHAPTER_12J':'<b>Rekisteröity voi toteuttaa yllämainitut oikeutensa ottamalla rekisterinpitäjään yhteyttä kohdassa 2 määriteltyjen yhteystietojen avulla, mieluiten sähköpostitse.</b>',
				'SESSION_EXPIRED':'Kirjautuminen on vanhentunut... automaattinen uloskirjaus 3 sekunnissa!',
				'MENU_VERSION':'v 22.03.09-G'
			}
		}
	}
}
