export default class LanguageModel {
	constructor() {
		this.languages = ['en','fi'];
		this.selected = 'fi';
		this.translation = {
			'en':{
				'USER_LOGIN_TITLE':'Login',
				'USER_EMAIL':'Email',
				'USER_PASSWORD':'Password',
				'USER_REGCODE':'Registration code',
				'USER_LOGIN_BTN_TXT':'Login',
				'USER_OPEN_SIGNUP_FORM':'Open signup form &raquo;',
				'USER_SIGNUP_TITLE':'Signup',
				'USER_SIGNUP_BTN_TXT':'Signup',
				'USER_SIGNUP_SENSORS_TXT':'You can also have sensors to measure temperature and humidity in your apartment. This data is shown only to you. Check the checkbox below if you want sensors. Due to limited number of sensors in this pilot, please be quick.',
				'USER_SIGNUP_SENSORS_CHECKBOX_LABEL':'Yes, I want sensors.',
				'USER_SIGNUP_GDPR_OK_1':'I have read the ',
				'USER_SIGNUP_GDPR_LINK_TXT':'GDPR statement',
				'USER_SIGNUP_GDPR_OK_2':' and give my consent.',
				'USER_SIGNUP_APARTMENT_NUMBER':'Apartment number',
				'USER_SIGNUP_APARTMENT_NOT_SELECTED':'Not selected',
				'USER_SIGNUP_APARTMENT_MUST_INPUT':'Must input <b>Apartment number</b>',
				'USER_PROPS_TITLE':'User Properties',
				'USER_PROPS_DESCRIPTION':'User can can view and modify own properties here.',
				'USER_PROPS_CHANGE_PASSWORD_BTN_TXT':'Change password',
				'USER_PROPS_GDPR':'Click this link to read the ',
				'USER_PROPS_ADMIN_DESCRIPTION':'Admin can view and edit RegCodes, view Users and associated ReadKeys.',
				'USER_PROPS_ADMIN_REGCODES':'RegCodes',
				'USER_PROPS_ADMIN_REGCODES_CREATE_BTN_TXT': 'Create new',
				'USER_PROPS_ADMIN_USERS':'Users',
				'USER_CHANGE_PASSWORD_TITLE':'Change password',
				'USER_OLD_PASSWORD':'Old password',
				'USER_NEW_PASSWORD':'New password',
				'ADMIN_START_LABEL':'Start',
				'ADMIN_END_LABEL':'End',
				'ADMIN_CREATE_NEW_REGCODE_TITLE':'Create a new RegCode',
				'ADMIN_CREATE_NEW_REGCODE_APA_ID':'Apartment ID',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_START_DATE':'Invalid start date',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_END_DATE':'Invalid end date',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_DATE_ORDER':'End must be after the start.',
				'ADMIN_EDIT_REGCODE_TITLE':'RegCode',
				'ADMIN_EDIT_REGCODE_DESCRIPTION':'Modify RegCodes validity period.',
				'ADMIN_EDIT_REGCODE_APARTMENT':'Apartment',
				'ADMIN_EDIT_READKEY_TITLE':'ReadKey',
				'ADMIN_EDIT_READKEY_DESCRIPTION':'Modify ReadKey validity period.',
				'BACK':'BACK',
				'CANCEL':'CANCEL',
				'SAVE':'SAVE',
				'UPDATE':'UPDATE',
				'VALIDATOR_NOT_VALID':' not valid',
				'VALIDATOR_MISSING':' missing',
				'VALIDATOR_TOO_SHORT':' too short',
				'VALIDATOR_NOT_A_NUMBER':' not a number',
				'VALIDATOR_MUST_BE_POSITIVE_NUMBER':' must be positive number',
				'VALIDATOR_MUST_BE_GREATER_THAN_ZERO':' must be greater than zero',
				'QUICK_LOGIN':'MOCKUP LOGIN',
				'QUICK_LOGIN_MESSAGE':'NOTE: This is a MOCKUP. You can use the login button below to login as "testuser@testdomain.com".',
				'FEEDBACK_BUILDING_TITLE':'Feedback about the whole building',
				'FEEDBACK_BUILDING_DESCRIPTION_1':'How do you feel about the building temperature today?',
				'FEEDBACK_BUILDING_DESCRIPTION_2':'Select smiley and/or write free text feedback and send.',
				'FEEDBACK_APARTMENT_TITLE':'Feedback about your apartment',
				'FEEDBACK_APARTMENT_DESCRIPTION_1':'How do you feel about your apartment temperature today?',
				'FEEDBACK_APARTMENT_DESCRIPTION_2':'Select smiley and/or write free text feedback and send.',
				'FEEDBACK_TEXT_COLD':'Cold',
				'FEEDBACK_TEXT_COOL':'Cool',
				'FEEDBACK_TEXT_SLIGHTLY_COOL':'Slightly Cool',
				'FEEDBACK_TEXT_HAPPY':'Happy',
				'FEEDBACK_TEXT_SLIGHTLY_WARM':'Slightly  Warm',
				'FEEDBACK_TEXT_WARM':'Warm',
				'FEEDBACK_TEXT_HOT':'Hot',
				'FEEDBACK_FREE_TEXT_LABEL':'Free text feedback',
				'FEEDBACK_SEND_FEEDBACK':'Send',
				'FEEDBACK_SENT_OK':'Thank you for your feedback!',
				'BUILDING_ELECTRICITY_TITLE':'Building electricity consumption',
				'BUILDING_HEATING_TITLE':'Building district heating',
				'BUILDING_CO2_TITLE':'Building CO<sub>2</sub> emissions',
				'BUILDING_CO2_DESCRIPTION':'This chart displays <b>EMISSION FACTORS</b> for electricity consumed and produced in Finland',
				'BUILDING_CO2_CONSUMPTION':'Consumption',
				'BUILDING_CO2_PRODUCTION':'Production',
				'USER_HEATING_TITLE':'Apartment temperature and humidity',
				'SESSION_EXPIRED':'Session has expired... logging out in 3 seconds!',
				'MENU_VERSION':'v 21.09.29'
			},
			'fi':{
				'USER_LOGIN_TITLE':'Kirjautuminen',
				'USER_EMAIL':'Sähköposti',
				'USER_PASSWORD':'Salasana',
				'USER_REGCODE':'Rekisteröintikoodi',
				'USER_LOGIN_BTN_TXT':'KIRJAUDU SISÄÄN',
				'USER_OPEN_SIGNUP_FORM':'Rekisteröityminen &raquo;',
				'USER_SIGNUP_TITLE':'Rekisteröityminen',
				'USER_SIGNUP_BTN_TXT':'Rekisteröidy',
				'USER_SIGNUP_SENSORS_TXT':'Asuntoon on mahdollista asentaa lämpötila- ja kosteusmittaus. Laita rasti alla olevaan ruutuun jos haluat mittarit. Koska mittareita on tässä kokeilussa rajoitettu määrä, toimi nopeasti.',
				'USER_SIGNUP_SENSORS_CHECKBOX_LABEL':'Kyllä, haluan mittarit.',
				'USER_SIGNUP_GDPR_OK_1':'Olen lukenut ',
				'USER_SIGNUP_GDPR_LINK_TXT':'GDPR tekstin',
				'USER_SIGNUP_GDPR_OK_2':' ja hyväksyn ehdot.',
				'USER_SIGNUP_APARTMENT_NUMBER':'Asunnon numero',
				'USER_SIGNUP_APARTMENT_NOT_SELECTED':'Ei valittu',
				'USER_SIGNUP_APARTMENT_MUST_INPUT':'<b>Asunnon numero</b> täytyy ilmoittaa</b>',
				'USER_PROPS_TITLE':'Omat tiedot',
				'USER_PROPS_DESCRIPTION':'Tällä sivulla käyttäjä voi katsoa ja muokata omia tietojaan.',
				'USER_PROPS_CHANGE_PASSWORD_BTN_TXT':'Vaihda salasana',
				'USER_PROPS_GDPR':'Täältä voit lukea ',
				'USER_PROPS_ADMIN_DESCRIPTION':'Ylläpitäjä voi nähdä ja muokata rekisteröintikoodeja ja lisäksi hallita kaikkien käyttäjien lukuavaimia.',
				'USER_PROPS_ADMIN_REGCODES':'Rekisteröintikoodit',
				'USER_PROPS_ADMIN_REGCODES_CREATE_BTN_TXT':'Luo uusi',
				'USER_PROPS_ADMIN_USERS':'Käyttäjät',
				'USER_CHANGE_PASSWORD_TITLE':'Salasanan vaihto',
				'USER_OLD_PASSWORD':'Vanha salasana',
				'USER_NEW_PASSWORD':'Uusi salasana',
				'ADMIN_START_LABEL':'Alkaa',
				'ADMIN_END_LABEL':'Loppuu',
				'ADMIN_CREATE_NEW_REGCODE_TITLE':'Uusi rekisteröintikoodi',
				'ADMIN_CREATE_NEW_REGCODE_APA_ID':'Asunnon ID',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_START_DATE':'Alkuaika väärin',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_END_DATE':'Loppuaika väärin',
				'ADMIN_CREATE_NEW_REGCODE_INVALID_DATE_ORDER':'Loppuaika ja alkuaika väärinpäin.',
				'ADMIN_EDIT_REGCODE_TITLE':'Rekisteröintikoodi',
				'ADMIN_EDIT_REGCODE_DESCRIPTION':'Voit muuttaa rekisteröintikoodin voimassaoloaikaa.',
				'ADMIN_EDIT_REGCODE_APARTMENT':'Asunto',
				'ADMIN_EDIT_READKEY_TITLE':'Lukuavain',
				'ADMIN_EDIT_READKEY_DESCRIPTION':'Voit muuttaa lukuavaimen voimassaoloaikaa.',
				'BACK':'TAKAISIN',
				'CANCEL':'PERU',
				'SAVE':'TALLETA',
				'UPDATE':'PÄIVITÄ',
				'VALIDATOR_NOT_VALID':' ei kelpaa',
				'VALIDATOR_MISSING':' puuttuu',
				'VALIDATOR_TOO_SHORT':' liian lyhyt',
				'VALIDATOR_NOT_A_NUMBER':' ei ole numero',
				'VALIDATOR_MUST_BE_POSITIVE_NUMBER':' täytyy olla positiivinen numero',
				'VALIDATOR_MUST_BE_GREATER_THAN_ZERO':' täytyy olla suurempi kuin nolla',
				'QUICK_LOGIN':'MOCKUP KIRJAUTUMINEN',
				'QUICK_LOGIN_MESSAGE':'HUOM: Tämä on MOCKUP. Voit kirjautua testikäyttäjänä suoraan alla olevasta napista.',
				'FEEDBACK_BUILDING_TITLE':'Palaute koskien koko taloa',
				'FEEDBACK_BUILDING_DESCRIPTION_1':'Miltä rakennuksen lämpötila tänään tuntuu?',
				'FEEDBACK_BUILDING_DESCRIPTION_2':'Valitse sopiva tunnetila ja/tai kirjoita vapaamuotoinen teksti ja lähetä.',
				'FEEDBACK_APARTMENT_TITLE':'Palaute koskien asuntoa',
				'FEEDBACK_APARTMENT_DESCRIPTION_1':'Miltä asuntosi lämpötila tänään tuntuu?',
				'FEEDBACK_APARTMENT_DESCRIPTION_2':'Valitse sopiva tunnetila ja/tai kirjoita vapaamuotoinen teksti ja lähetä.',
				'FEEDBACK_TEXT_COLD':'Kylmä',
				'FEEDBACK_TEXT_COOL':'Viileä',
				'FEEDBACK_TEXT_SLIGHTLY_COOL':'Hieman viileä',
				'FEEDBACK_TEXT_HAPPY':'Tyytyväinen',
				'FEEDBACK_TEXT_SLIGHTLY_WARM':'Hieman lämmin',
				'FEEDBACK_TEXT_WARM':'Lämmin',
				'FEEDBACK_TEXT_HOT':'Kuuma',
				'FEEDBACK_FREE_TEXT_LABEL':'Vapaamuotoinen palaute',
				'FEEDBACK_SEND_FEEDBACK':'Lähetä',
				'FEEDBACK_SENT_OK':'Kiitos palautteestasi!',
				'BUILDING_ELECTRICITY_TITLE':'Rakennuksen sähkönkulutus',
				'BUILDING_HEATING_TITLE':'Rakennuksen kaukolämmön kulutus',
				'BUILDING_CO2_TITLE':'Rakennuksen hiilijalanjälki',
				'BUILDING_CO2_DESCRIPTION':'Sähkön kulutuksen ja tuotannon <b>päästökertoimet</b> Suomessa',
				'BUILDING_CO2_CONSUMPTION':'Kulutus',
				'BUILDING_CO2_PRODUCTION':'Tuotanto',
				'USER_HEATING_TITLE':'Asunnon lämpötila ja kosteus',
				'SESSION_EXPIRED':'Kirjautuminen on vanhentunut... automaattinen uloskirjaus 3 sekunnissa!',
				'MENU_VERSION':'v 21.09.29'
			}
		}
	}
}
